[package]
name = "rusty-2022"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly-2022-12-09"

[dependencies]
camino = "1.1.1"
itertools = "0.10.5"
nom = "7.1.1"

[unstable]
get_many_mut = true
